server:
  port: 8085
spring:
  application:
    name: springboot-ollama
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma3:1b-it-qat
          temperature: 0.1
          max-tokens: 512
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG


