server:
  port: 8085
spring:
  application:
    name: springboot-ollama-tools
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2:3b
#          model: gemma3:4b-it-qat
          temperature: 0.1
#          max-tokens: 1024

logging:
  level:
    com.fabiankevin.tools: DEBUG
    org.springframework.ai.chat.client.advisor: DEBUG


