server:
  port: 8086
spring:
  application:
    name: springboot-toolcallback-api
  ai:
    ollama:
      chat:
        model: llama3.2:3b
        options:
          model: llama3.2:3b
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG


